config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  root "home#index"

  resources :citizens, except: [:show, :destroy]

  namespace :api do
    resources :addresses, only: :index
    resources :toggle_status_citizens, only: :update
  end

  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  validates :zip_code, presence: true
  validates :street_name, presence: true
  validates :neighborhood, presence: true
  validates :state, inclusion: { in: AddressStates.list }
  validates :city, presence: true

  has_enumeration_for :state, with: AddressStates
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citizen.rb
# frozen_string_literal: true

class Citizen < ApplicationRecord
  validates :name, presence: true
  validates :cpf, presence: true, cpf: true
  validates :cns, presence: true, "CnsBrazil::Cns": true
  validates :email, presence: true, email: true
  validates :born_in, presence: true, birth_date: true
  validates :phone, presence: true, phone: true

  has_one :address, as: :addressable, dependent: :nullify

  accepts_nested_attributes_for :address

  mount_uploader :photo, Citizens::PhotoUploader
end

app/controllers/api/addresses_controller.rb
# frozen_string_literal: true

module API
  class AddressesController < ApplicationController
    def index
      render json: Address.new(address_params)
    end

    def address_params
      Addresses::FetchByZipCode.call(zip_code: params[:zip_code]).address
    end
  end
end

app/controllers/api/base_controller.rb
# frozen_string_literal: true

module API
  class BaseController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    def record_not_found
      render json: { success: false }, status: :not_found
    end
  end
end

app/controllers/api/toggle_status_citizens_controller.rb
# frozen_string_literal: true

module API
  class ToggleStatusCitizensController < API::BaseController
    def update
      render json: { success: citizen.update(enabled: !citizen.enabled) }
    end

    private

    def citizen
      @citizen ||= CitizensQuery.new.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/citizens_controller.rb
# frozen_string_literal: true

class CitizensController < ApplicationController
  def index
    @citizens = query.search(params[:term]).paginate(params[:page])

    render(render_index_options)
  end

  def new
    @citizen = query.build
  end

  def edit
    @citizen = query.find(params[:id])
  end

  def create
    service = Citizens::Save.call(params: citizen_params)

    if service.success?
      redirect_to citizens_path, notice: t(".success")
    else
      @citizen = service.citizen
      render :new, status: :unprocessable_entity
    end
  end

  def update
    service = Citizens::Save.call(id: params[:id], params: citizen_params)

    if service.success?
      redirect_to citizens_path, notice: t(".success")
    else
      @citizen = service.citizen
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def query
    @query ||= CitizensQuery.new
  end

  def render_index_options
    return :index unless turbo_frame_request?

    { partial: "citizens/citizens_table" }
  end

  def citizen_params
    params.require(:citizen)
          .permit(citizen_attributes, address_attributes:)
  end

  def citizen_attributes
    [:name, :email, :phone, :cns, :cpf, :born_in, :photo]
  end

  def address_attributes
    [:id, :zip_code, :street_name, :building_number, :neighborhood, :city, :state, :ibge]
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def app_name
    ENV.fetch("APP_NAME")
  end

  def app_version
    File.read("VERSION").strip
  end
end

app/helpers/translation_helper.rb
# frozen_string_literal: true

module TranslationHelper
  ##
  # Public: Translate a model name.
  #
  # model: Model class.
  # count: Count.
  #
  # Examples:
  #
  #   <%= tm(Post) %>
  #   # => 'Artigo'
  #
  #   <%= tm(Post, 2) %>
  #   # => 'Artigos'
  #
  # Returns translated model.
  def translate_model_name(model, count = 1)
    model.model_name.human(count:)
  end
  alias tm translate_model_name

  ##
  # Public: Translate a model name pluralized.
  #
  # model: Model class.
  #
  # Examples:
  #
  #   <%= tmp(Post) %>
  #   # => 'Artigos'
  #
  # Returns translated model pluralized.
  def translate_model_name_pluralized(model)
    translate_model_name(model, 2)
  end
  alias tmp translate_model_name_pluralized

  ##
  # Public: Translate a model submit button.
  #
  # model: Model class.
  #
  # Examples:
  #
  #   <%= tmb(Post, :create) %>
  #   => <button name="button" type="submit" class="btn btn-primary">
  #   =>   <i class="bi bi-save2"> </i>Criar Artigo
  #   => </button>
  #
  #   <%= tmb(Post, :update) %>
  #   => <button name="button" type="submit" class="btn btn-primary">
  #   =>   <i class="bi bi-save2"> </i>Atualizar Artigo
  #   => </button>
  #
  # Returns translated model pluralized.
  def translate_model_button(model, kind)
    t("helpers.submit.#{kind}", model: tm(model))
  end
  alias tmb translate_model_button

  ##
  # Public: Translate a model attribute.
  #
  # model: Model class.
  # attribute: Attribute name.
  # count: Count.
  #
  # Examples
  #
  #   <%= ta(Post, :title) %>
  #   # => 'Titulo'
  #
  #   <%= ta(Post, :title, 2) %>
  #   # => 'Titulos'
  #
  # Returns translated model's attribute.
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, count:)
  end
  alias ta translate_model_attribute
end

app/views/addresses/_form.html.erb
<div class="address-wrapper" data-controller="addresses">
  <%= form.hidden_field(:ibge, class: "ibge") %>

  <div class="row">
    <div class="col-sm-3">
      <%= form.input(:zip_code, input_html: { data: { mask: "cep", action: "keyup->addresses#find" } }) %>
    </div>

    <div class="col-sm-5">
      <%= form.input(:street_name, input_html: { class: "street-name" }) %>
    </div>

    <div class="col-sm-4">
      <%= form.input(:building_number, required: true) %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <%= form.input(:neighborhood, input_html: { class: "neighborhood" }) %>
    </div>

    <div class="col-sm-4">
      <%= form.input(:city,
                     input_html: { class: "city bg-body-secondary" },
                     placeholder: ta(Address, :city_placeholder)) %>
    </div>

    <div class="col-sm-4">
      <%= form.input(:state,
                     collection: AddressStates.to_a,
                     input_html: { class: "state bg-body-secondary" },
                     include_blank: ta(Address, :state_placeholder)) %>
    </div>
  </div>
</div>

app/views/citizens/_citizens_table.html.erb
<%= turbo_frame_tag "citizens" do %>
  <% if @citizens.blank? %>
    <%= render("shared/alerts/warning", message: t(".not_found")) %>
  <% else %>
    <table class="table table-sm table-hover table-bordered rounded-5">
      <thead class="table-light">
        <tr>
          <th scope="col"><%= ta(Citizen, :photo) %></th>
          <th scope="col"><%= ta(Citizen, :name) %></th>
          <th scope="col"><%= ta(Citizen, :email) %></th>
          <th scope="col"><%= ta(Citizen, :cpf) %></th>
          <th scope="col"><%= ta(Citizen, :cns) %></th>
          <th scope="col"><%= ta(Citizen, :enabled) %></th>
          <th width="70"></th>
        </tr>
      </thead>
      <tbody data-controller="citizens">
        <% @citizens.each do |citizen| %>
          <tr id="<%= dom_id(citizen) %>">
            <td class="text-center">
              <% if citizen.photo.present? %>
                <%= image_tag(citizen.photo.thumb.url, class: "rounded") %>
              <% end %>
            </td>
            <td><%= citizen.name %></td>
            <td><%= citizen.email %></td>
            <td><%= citizen.cpf %></td>
            <td><%= citizen.cns %></td>
            <td class="text-center">
              <div class="form-check form-switch">
                <%= check_box_tag(:enabled, citizen.id, citizen.enabled?,
                                  data: { action: "change->citizens#toggleStatus" },
                                  class: "form-check-input") %>
              </div>
            </td>
            <td class="text-center">
              <%= render("shared/link_to/edit", record: citizen) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= render("shared/pagination/links", collection: @citizens) %>
  <% end %>
<% end %>

app/views/citizens/_form.html.erb
<%= simple_form_for(citizen) do |form| %>
  <div class="card mb-3">
    <div class="card-header">
      <h4 class="m-0"><%= t(".info") %></h4>
    </div>

    <div class="card-body">
      <div class="row">
        <div class="col-8">
          <%= form.input(:name) %>
        </div>

        <div class="col-4">
          <div class="input-group mb-3">
            <div class="form-floating">
              <%= form.file_field(:photo, class: "form-control") %>
              <%= form.label(:photo) %>
            </div>

            <% if citizen.photo.present? %>
              <span class="input-group-text">
                <%= image_tag(citizen.photo.thumb.url, class: "rounded") %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-6"><%= form.input(:email) %></div>

        <div class="col-6">
          <%= form.input(:phone, input_html: { data: { mask: "phone" } }) %>
        </div>
      </div>

      <div class="row">
        <div class="col-4">
          <%= form.input(:cns, input_html: { data: { mask: "cns" } }) %>
        </div>

        <div class="col-4">
          <%= form.input(:cpf, input_html: { data: { mask: "cpf" } }) %>
        </div>

        <div class="col-4">
          <%= form.input(:born_in, html5: true, input_html: { max: Date.yesterday }) %>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <h4 class="m-0"><%= tm(Address) %></h4>
    </div>

    <div class="card-body">
      <%= form.simple_fields_for(:address) do |fa| %>
        <%= render("addresses/form", form: fa) %>
      <% end %>
    </div>
  </div>

  <%= render("shared/form/actions", record: citizen, back_url: citizens_path) %>
<% end %>

app/views/citizens/_form_filter.html.erb
<%= simple_form_for("",
                    url: citizens_path,
                    method: :get,
                    data: {
                      turbo_frame: "citizens",
                      controller: "search",
                      action: "change->search#perform"
                    },
                    class: "m-0") do |form| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="input-group">
        <%= form.text_field :term, value: params[:term],
                                   class: "form-control",
                                   data: { action: "keyup->search#perform" },
                                   placeholder: "Buscar por..." %>

        <button class="btn btn-primary" type="submit">
          <i class="bi bi-search"></i> Buscar
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/citizens/edit.html.erb
<%= render("shared/page_title/index", page_title: t(".title")) %>

<%= render("form", citizen: @citizen) %>

app/views/citizens/index.html.erb
<%= render("shared/page_title/index", page_title: t(".title"), link: new_citizen_path) %>

<div class=" mb-3">
  <div class="">
    <%= render "form_filter" %>
  </div>
</div>

<%= render "citizens_table" %>

app/views/citizens/new.html.erb
<%= render("shared/page_title/index", page_title: t(".title")) %>

<%= render("form", citizen: @citizen) %>

app/views/home/index.html.erb
<h1><%= app_name %></h1>

<p data-controller="home"></p>

app/views/layouts/_footer.html.erb
<footer class="border-top text-center p-3 bg-dark-subtle">
  <%= app_name %> - <%= app_version %>
</footer>

app/views/layouts/_loading.html.erb
<section id="loading" class="visually-hidden z-3">
  <div class="d-flex justify-content-center align-items-center position-fixed translate-middle min-vh-100 vw-100 top-50 start-50">
    <div class="bg-dark-subtle opacity-75 min-vh-100 min-vw-100 position-absolute"></div>
    <div class="spinner-border p-5 m-5" role="status">
      <span class="visually-hidden">.label</span>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<header id="menu" class="p-3 text-bg-dark">
  <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <%= link_to(root_path, class: "d-flex align-items-center img-thumbnail mb-lg-0 text-white") do %>
      <%= image_tag("logo.png", height: 35) %>
    <% end %>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <li><%= link_to("Home", root_path, class: "nav-link px-2 text-white") %></li>
      <li><%= link_to(tmp(Citizen), citizens_path, class: "nav-link px-2 text-white") %></li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= app_name %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag("application", "data-turbo-track": "reload") %>
    <%= javascript_include_tag("application", "data-turbo-track": "reload", defer: true) %>

    <%= favicon_link_tag("icon.png") %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body class="min-vh-100 d-flex flex-column">
    <%= render("layouts/loading") %>
    <%= render("layouts/navbar") %>

    <main id="app" class="flex-grow-1 mt-3">
      <div class="container" data-controller="masks">
        <%= render("shared/alerts/success", message: notice) if notice.present? %>

        <%= yield %>
      </div>
    </main>

    <%= render("layouts/footer") %>
  </body>
</html>

app/views/shared/alerts/_success.html.erb
<%= tag.section(message, class: "alert alert-success m-0") %>

app/views/shared/alerts/_warning.html.erb
<%= tag.section(message, class: "alert alert-warning m-0") %>

app/views/shared/form/_actions.html.erb
<div class="mt-2 text-end">
  <%= link_to(back_url, class: "btn btn-outline-secondary") do %>
    <%= t(".back_link") %>
  <% end %>

  <%= button_tag(nil, class: "btn btn-primary") do %>
    <%= tmb(record.class, record.new_record? ? :create : :update) %>
  <% end %>
</div>

app/views/shared/link_to/_edit.html.erb
<%= link_to(t(".label"),
            [:edit, record],
            class: "btn btn-sm btn-outline-success") %>

app/views/shared/page_title/_index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <div class="<%= "col-#{defined?(link) ? 8 : 12}" %>">
    <h1 class="h2 mb-0"><%= page_title %></h1>
  </div>

  <% if defined?(link) %>
    <%= tag.div(link, class: "col-4 text-end") do %>
      <%= link_to(t(".create"), link, class: "btn btn-sm btn-outline-primary") %>
    <% end %>
  <% end %>
</div>

app/views/shared/pagination/_links.html.erb
<%= paginate(collection, theme: "bs5", pagination_class: "pagination-sm m-0 justify-content-center") %>